# Generated by Django 5.2.8 on 2025-11-26 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0002_welcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.ImageField(blank=True, default='icons/default.png', upload_to='icons/', verbose_name='图标')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('img', models.ImageField(default='goods/default.png', upload_to='goods/', verbose_name='主图')),
                ('description', models.TextField(blank=True, verbose_name='商品详情')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='库存')),
                ('is_hot', models.BooleanField(default=False, verbose_name='是否热销')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新品')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='hardware_app.category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
