# Generated by Django 5.2.8 on 2025-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0003_category_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tab名称')),
                ('page_path', models.CharField(help_text='例如: /pages/home/home', max_length=100, verbose_name='页面路径')),
                ('icon', models.ImageField(upload_to='tabbar/', verbose_name='未选中图标')),
                ('selected_icon', models.ImageField(upload_to='tabbar/', verbose_name='选中图标')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '底部导航配置',
                'verbose_name_plural': '底部导航配置',
                'ordering': ['order'],
            },
        ),
    ]
