# Generated by Django 5.2.8 on 2025-11-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0005_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='spec_name',
            field=models.CharField(default='标准规格', max_length=100, verbose_name='规格名称'),
        ),
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规格名称')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='如果不填则使用商品默认价格', max_digits=10, null=True, verbose_name='规格价格')),
                ('stock', models.PositiveIntegerField(default=100, verbose_name='库存')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='hardware_app.goods', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品规格',
                'verbose_name_plural': '商品规格',
            },
        ),
    ]
