# Generated by Django 5.2.8 on 2025-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0006_cartitem_spec_name_goodsspec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='goodsspec',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='如果不填则使用商品默认价格', max_digits=10, null=True, verbose_name='规格价格'),
        ),
    ]
