# Generated by Django 5.2.8 on 2025-11-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0008_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='价格'),
        ),
    ]
