# Generated by Django 5.2.8 on 2025-11-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware_app', '0009_alter_goods_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='用户ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单号')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('address_snapshot', models.TextField(verbose_name='收货信息快照')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('spec_name', models.CharField(max_length=100, verbose_name='规格')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('count', models.PositiveIntegerField(verbose_name='数量')),
                ('img', models.CharField(blank=True, max_length=255, verbose_name='图片快照')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hardware_app.order')),
            ],
        ),
    ]
